### PR TITLE
Lots of updates to rendering and multiplayer

### PR DESCRIPTION
**Pull request by KittyTristy**

### CODE REVIEW

**Comment by KittyTristy** [comment]
Hm.. maybe some of these commits should be squashed, particularly merge branch commits.

**Comment by cptmashek** [comment]
Agreed!

**Comment by KittyTristy** [comment]
Except that I don't see how to squash those.  They literally don't appear as commits to pick when I do a rebase.

**Comment by KittyTristy** [comment]
I have an idea.

**Pull request closed without merging**
